ITHOOT/Controllers/DeveloperOnProjectController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ITHOOT.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class DeveloperOnProjectController : Controller
    {
        IProjectService projectService;

        public DeveloperOnProjectController(IProjectService projectService)
        {
            this.projectService = projectService;
        }

        [HttpGet]
        public async Task<IActionResult> AddDeveloperOnProject(Guid projectId,[FromServices] IDeveloperService developerService)
        {
            if (projectId == Guid.Empty) 
                return BadRequest();
            var entry = await projectService.GetAsync(projectId);
            if (entry == null)
                return NotFound();
            DeveloperOnProjectViewModel model = new DeveloperOnProjectViewModel { ProjectId = entry.Id };
            var projects = await projectService.GetAllAsync();

            ViewData["Projects"] = new SelectList(projects, "Id", "Name", entry.Id);
            var developers = await developerService.GetAllAsync();
            ViewData["Developers"] = new SelectList(developers, "Id", "Name");
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddDeveloperOnProject(DeveloperOnProjectViewModel model, [FromServices] IDeveloperService developerService)
        {
            if (model.DeveloperId == Guid.Empty)
            { 
                ModelState.AddModelError("DeveloperId", "Не обраний розробник");
            }
            if (ModelState.IsValid)
            {
                var entryProject = await projectService.GetAsync(model.ProjectId);
                var entryDeveloper = await developerService.GetAsync(model.DeveloperId);
                if (entryDeveloper == null || entryProject==null)
                    return NotFound();

                entryProject.Developers.Add(entryDeveloper);

                await projectService.UpdateAsync(entryProject.ToDTO());

                return RedirectToAction("Detalis", "Project", new { id = model.ProjectId });
            }
            var projects = await projectService.GetAllAsync();
            ViewData["Projects"] = new SelectList(projects, "Id", "Name", model.ProjectId);
            var developers = await developerService.GetAllAsync();
            ViewData["Developers"] = new SelectList(developers, "Id", "Name",model.DeveloperId);
            return PartialView(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> RemoveDeveloperOnProject(Guid projectId, Guid developerId)
        {
            var entryProject = await projectService.GetAsync(projectId);
            var entryDeveloper = entryProject.Developers.First(p => p.Id == developerId);
            if (entryDeveloper == null || entryProject == null)
                return NotFound();
            entryProject.Developers.Remove(entryDeveloper);
            await projectService.UpdateAsync(entryProject.ToDTO());
            return RedirectToAction("Detalis", "Project", new { id = projectId });
        }
    }
}

ITHOOT/Controllers/ProjectController.cs
using BLL.Core;
using Microsoft.AspNetCore.Mvc;
using Mapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;

namespace ITHOOT.Controllers
{
    public class ProjectController : Controller
    {
        IProjectService projectService;

        public ProjectController(IProjectService projectService)
        {
            this.projectService = projectService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await projectService.GetAllAsync();
            return PartialView(model.ToList());
        }
        [HttpGet]
        public async Task<IActionResult> Detalis(Guid id)
        {
            var model = await projectService.GetAsync(id);
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Create([FromServices] IClientService clientService)
        {
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients,"Id","Name");
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProjectModel model,[FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await projectService.AddAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name",model.ClientId);
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id,[FromServices] IClientService clientService)
        {
            if (Id == Guid.Empty) 
                return BadRequest();

            var model = await projectService.GetAsync(Id);

            if (model == null) 
                return NotFound();

            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name",model.ClientId);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProjectModel model, [FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await projectService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name", model.ClientId);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();
            try
            {
                ProjectModel model = await projectService.GetAsync(id);
                await projectService.RemoveAsync(model.ToDTO());
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
       
        
    }
}

ITHOOT/Views/Project/Create.cshtml
@model ProjectModel
<div class="row justify-content-center">
    <div class="col-md-8">
        <form asp-controller="Project" asp-action="Create" onsubmit="return postQuery(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="@ViewBag.Clients"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
            <div>
                <a class="btn btn-sm btn-primary text-white" onclick="getRequest('@Url.Action("Index", "Project", null, Context.Request.Scheme)')">Назад</a>
            </div>
        </form>
    </div>
</div>

ITHOOT/Views/Project/Detalis.cshtml
@model ProjectModel

<div class="d-flex flex-column bg-light m-2 justify-content-around">
    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex">
            <p class="p-1">@Html.DisplayNameFor(model => model.Id)</p>
            <p class="p-1">@Html.DisplayFor(model => Model.Id)</p>
        </div>
        <div class="d-flex">
            <p class="p-1">@Html.DisplayNameFor(model => model.Name)</p>
            <p class="p-1">@Html.DisplayFor(model => Model.Name)</p>
        </div>
        <div class="d-flex">
            <p class="p-1">@Html.DisplayNameFor(model => model.Client)</p>
            <p class="p-1">@Html.DisplayFor(model => Model.Client.Name)</p>
        </div>
    </div>
    <p class="text-uppercase">@Html.DisplayNameFor(model => model.Developers)</p>
    <div class="mb-3 row">

        @foreach (DeveloperModel developer in Model.Developers)
        {
<div class="d-flex justify-content-between col-6">
    <p>@Html.DisplayFor(model => developer.Name)</p>
    <p>@Html.DisplayFor(model => developer.Position.Name)</p>
    <form method="post" asp-action="RemoveDeveloperOnProject" asp-route-developerId="@developer.Id" asp-route-projectId="@Model.Id" asp-controller="DeveloperOnProject" onsubmit="return jQueryAjaxDelete(this);">
        <input class="btn btn-secondary" type="submit" value="Вилучити розробника" />
    </form>
</div>}
    </div>



    <div class="d-flex">
        <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Index", "Project", new { id = Model.Id }, Context.Request.Scheme)')">Назад</a> |
        <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Edit", "Project", new { id = Model.Id }, Context.Request.Scheme)')">Редагувати</a> |
        <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("AddDeveloperOnProject", "DeveloperOnProject", new { projectId = Model.Id }, Context.Request.Scheme)')">Додати розробника</a> |
        <form asp-action="Delete" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxDeleteDeveloperInProject(this);">
            <input class="btn btn-danger" type="submit" value="Видалити" />
        </form>
    </div>
</div>

ITHOOT/Views/Project/Edit.cshtml
@model ProjectModel
<div class="row justify-content-center">
    <div class="col-md-8">
        <form method="post" asp-controller="Project" asp-action="Edit" onsubmit="return postQuery(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="@ViewBag.Clients"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div>
                <a class="btn btn-sm btn-primary text-white" onclick="getRequest('@Url.Action("Index", "Project", null, Context.Request.Scheme)')">Return</a>
            </div>
        </form>
    </div>
</div>

ITHOOT/Views/Project/Index.cshtml
@model IEnumerable<ProjectModel>


<div>
    <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Create", "Project", null, Context.Request.Scheme)')">Add new</a>
</div>
@foreach (ProjectModel item in Model)
{
    <div class="d-flex flex-column bg-light m-2 justify-content-around">
        <div class="d-flex justify-content-between">
            <div class="d-flex">
                <p class="p-1">@Html.DisplayNameFor(model => model.Id)</p>
                <p class="p-1">@Html.DisplayFor(model => item.Id)</p>
            </div>
            <div class="d-flex">
                <p class="p-1">@Html.DisplayNameFor(model => model.Name)</p>
                <p class="p-1">@Html.DisplayFor(model => item.Name)</p>
            </div>
            <div class="d-flex">
                <p class="p-1">@Html.DisplayNameFor(model => model.Client)</p>
                <p class="p-1">@Html.DisplayFor(model => item.Client.Name)</p>
            </div>
        </div>
        <div class="d-flex">
            <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Edit", "Project", new { id = item.Id }, Context.Request.Scheme)')">Edit</a> |
            <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Detalis", "Project", new { id = item.Id }, Context.Request.Scheme)')">Details</a> |
            <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this);">
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form>
        </div>
    </div>
}