ITHOOT_Razor/Pages/Client/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataLayer;
using Entity;

namespace ITHOOT_Razor.Pages.Client
{
    public class CreateModel : PageModel
    {
        private readonly DataLayer.AppContext _context;

        public CreateModel(DataLayer.AppContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ClientEntity ClientEntity { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Clients.Add(ClientEntity);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ITHOOT_Razor/Pages/Client/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Entity;

namespace ITHOOT_Razor.Pages.Client
{
    public class DeleteModel : PageModel
    {
        private readonly DataLayer.AppContext _context;

        public DeleteModel(DataLayer.AppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ClientEntity ClientEntity { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ClientEntity = await _context.Clients.FirstOrDefaultAsync(m => m.Id == id);

            if (ClientEntity == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ClientEntity = await _context.Clients.FindAsync(id);

            if (ClientEntity != null)
            {
                _context.Clients.Remove(ClientEntity);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ITHOOT_Razor/Pages/Client/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Entity;

namespace ITHOOT_Razor.Pages.Client
{
    public class DetailsModel : PageModel
    {
        private readonly DataLayer.AppContext _context;

        public DetailsModel(DataLayer.AppContext context)
        {
            _context = context;
        }

        public ClientEntity ClientEntity { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ClientEntity = await _context.Clients.FirstOrDefaultAsync(m => m.Id == id);

            if (ClientEntity == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ITHOOT_Razor/Pages/Client/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Entity;

namespace ITHOOT_Razor.Pages.Client
{
    public class EditModel : PageModel
    {
        private readonly DataLayer.AppContext _context;

        public EditModel(DataLayer.AppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ClientEntity ClientEntity { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ClientEntity = await _context.Clients.FirstOrDefaultAsync(m => m.Id == id);

            if (ClientEntity == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ClientEntity).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClientEntityExists(ClientEntity.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ClientEntityExists(Guid id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

ITHOOT_Razor/Pages/Client/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Entity;
using BLL.Core;
using Model;
using Mapper;

namespace ITHOOT_Razor.Pages.Client
{
    public class IndexModel : PageModel
    {
        private readonly DataLayer.AppContext _context;

        public IndexModel(DataLayer.AppContext context)
        {
            _context = context;
        }
        public IList<ClientEntity> ClientsEntity { get;set; }

        
        [BindProperty]
        public ClientEntity ClientEntity { get; set; }
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Clients.Add(ClientEntity);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            if (model == null)
                return NotFound();

            await clientService.RemoveAsync(model.ToDTO());

            return RedirectToPage("./Index");
        }
        public async Task OnGetAsync()
        {
            ClientsEntity = await _context.Clients.ToListAsync();
        }
        public async Task<IActionResult> OnGetEditAsync(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            return RedirectToPage("./Index");
        }


        public async Task<IActionResult> OnPostEditAsync(ClientModel model, [FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await clientService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return RedirectToPage("./Index");
        }
    }
}

ITHOOT_Razor/Pages/Client/Create.cshtml
@page
@model ITHOOT_Razor.Pages.Client.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_LayoutNobar.cshtml";
}

<h1>Create</h1>

<h4>ClientEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger" ></div>
            <div class="form-group">
                <label asp-for="ClientEntity.Name" class="control-label"></label>
                <input asp-for="ClientEntity.Name" class="form-control" />
                <span asp-validation-for="ClientEntity.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITHOOT_Razor/Pages/Client/Delete.cshtml
@page
@model ITHOOT_Razor.Pages.Client.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientEntity</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientEntity.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClientEntity.Name)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="ClientEntity.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ITHOOT_Razor/Pages/Client/Details.cshtml
@page
@model ITHOOT_Razor.Pages.Client.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClientEntity</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClientEntity.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClientEntity.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.ClientEntity.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

ITHOOT_Razor/Pages/Client/Edit.cshtml
@page
@model ITHOOT_Razor.Pages.Client.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ClientEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientEntity.Name" class="control-label"></label>
                <input asp-for="ClientEntity.Name" class="form-control" />
                <span asp-validation-for="ClientEntity.Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ClientEntity.Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITHOOT_Razor/Pages/Client/Index.cshtml
@page
@model ITHOOT_Razor.Pages.Client.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function(){

            $('#buttonCreate').click(function(){
                $.ajax({
                    type: 'GET',
                    url: '@Url.Page("/Client/Create")',
                    success: function (result) {
                        $('#result1').html(result);
                    }
                });
            });
        });

    </script>
    
}
<fieldset>
    <form asp-page-handler="Create">
        <input type="button" class="btn btn-primary" value="Create new" id="buttonCreate" />
        <br />
        <span id="result1"></span>
    </form>
</fieldset>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientsEntity[0].Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ClientsEntity)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <form asp-page-handler="Delete" asp-route-id="@item.Id">
                        <input class="btn btn-danger" type="submit" value="Delete" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>