ITHOOT/Controllers/ClientController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Mvc;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class ClientController : Controller
    {
        public async Task<IActionResult> Index([FromServices] IClientService clientService)
        {
            var model = await clientService.GetAllAsync();
            return PartialView(model.ToList());
        }

        [HttpGet]
        public IActionResult Create() => PartialView();

        [HttpPost]
        public async Task<IActionResult> Create(ClientModel model,[FromServices] IClientService clientService)
        {
            model.Id = Guid.NewGuid();
            await clientService.AddAsync(model.ToDTO());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClientModel model, [FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await clientService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            if (model == null) 
                return NotFound();

            await clientService.RemoveAsync(model.ToDTO());

            return RedirectToAction("Index");
        }
    }
}

ITHOOT/Controllers/DeveloperController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class DeveloperController : Controller
    {
        public async Task<IActionResult> Index([FromServices] IDeveloperService developerService)
        {
            var model = await developerService.GetAllAsync();
            return PartialView(model.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Create([FromServices] IPositionService positionService)
        {
            var positions = (await positionService.GetAllAsync());
            ViewData["Positions"] = new SelectList(positions, "Id", "Name");
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DeveloperModel model, [FromServices] IDeveloperService developerService, [FromServices] IPositionService positionService)
        {
            if(ModelState.IsValid)
            {
                await developerService.AddAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            var positions = (await positionService.GetAllAsync());
            ViewData["Positions"] = new SelectList(positions, "Id", "Name",model.PositionId);
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id,[FromServices] IDeveloperService developerService,[FromServices] IPositionService positionService)
        {
            var model = await developerService.GetAsync(id);
            var positions = await positionService.GetAllAsync();
            ViewData["Positions"] = new SelectList(positions, "Id", "Name",model.PositionId);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(DeveloperModel model, [FromServices] IDeveloperService developerService, [FromServices] IProjectService projectService, [FromServices] IPositionService positionService)
        {
            if (ModelState.IsValid)
            {
                await developerService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            else
            {
                var positions = (await positionService.GetAllAsync()).Select(x => x);
                ViewData["Position"] = new SelectList(positions, "Id", "Name", model.PositionId);
                return PartialView(model);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id,[FromServices] IDeveloperService developerService)
        {
            if (id == Guid.Empty) return BadRequest();
            try
            {
                DeveloperModel model = await developerService.GetAsync(id);
                await developerService.RemoveAsync(model.ToDTO());
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }

    }
}

ITHOOT/Controllers/PositionController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Mvc;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class PositionController : Controller
    {
        IPositionService positionService;
        public PositionController(IPositionService positionService)
        {
            this.positionService = positionService;
        }
        public async Task<IActionResult> Index()
        {
            var model =await positionService.GetAllAsync();
            return PartialView(model.ToList());
        }
        [HttpGet]
        public IActionResult Create() => PartialView();
        [HttpPost]
        public async Task<IActionResult> Create(PositionModel model)
        {
            if (ModelState.IsValid)
            {
                await positionService.AddAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await positionService.GetAsync(id);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PositionModel model)
        {
            if (ModelState.IsValid)
            {
                await positionService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }
        [HttpPost] 
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();
            try
            {
                PositionModel model = await positionService.GetAsync(id);
                await positionService.RemoveAsync(model.ToDTO());
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
    }
}

ITHOOT/Controllers/ProjectController.cs
using BLL.Core;
using Microsoft.AspNetCore.Mvc;
using Mapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;

namespace ITHOOT.Controllers
{
    public class ProjectController : Controller
    {
        IProjectService projectService;

        public ProjectController(IProjectService projectService)
        {
            this.projectService = projectService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await projectService.GetAllAsync();
            return PartialView(model.ToList());
        }
        [HttpGet]
        public async Task<IActionResult> Detalis(Guid id)
        {
            var model = await projectService.GetAsync(id);
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Create([FromServices] IClientService clientService)
        {
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients,"Id","Name");
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProjectModel model,[FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await projectService.AddAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name",model.ClientId);
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id,[FromServices] IClientService clientService)
        {
            if (Id == Guid.Empty) 
                return BadRequest();

            var model = await projectService.GetAsync(Id);

            if (model == null) 
                return NotFound();

            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name",model.ClientId);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProjectModel model, [FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await projectService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            var clients = await clientService.GetAllAsync();
            ViewData["Clients"] = new SelectList(clients, "Id", "Name", model.ClientId);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();
            try
            {
                ProjectModel model = await projectService.GetAsync(id);
                await projectService.RemoveAsync(model.ToDTO());
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
       
        
    }
}

ITHOOT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] ITHOOT - project </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ITHOOT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark pointer" onclick="getRequest('@Url.Action("Index", "Client", null, Context.Request.Scheme)')">Client</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark pointer" onclick="getRequest('@Url.Action("Index", "Developer", null, Context.Request.Scheme)')">Developer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pointer text-dark" onclick="getRequest('@Url.Action("Index", "Position", null, Context.Request.Scheme)')">Position</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pointer text-dark" onclick="getRequest('@Url.Action("Index", "Project", null, Context.Request.Scheme)')">Project</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main id="main" role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>