ITHOOT/Controllers/ClientController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Mvc;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class ClientController : Controller
    {
        public async Task<IActionResult> Index([FromServices] IClientService clientService)
        {
            var model = await clientService.GetAllAsync();
            return PartialView(model.ToList());
        }

        [HttpGet]
        public IActionResult Create() => PartialView();

        [HttpPost]
        public async Task<IActionResult> Create(ClientModel model,[FromServices] IClientService clientService)
        {
            model.Id = Guid.NewGuid();
            await clientService.AddAsync(model.ToDTO());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClientModel model, [FromServices] IClientService clientService)
        {
            if (ModelState.IsValid)
            {
                await clientService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id, [FromServices] IClientService clientService)
        {
            var model = await clientService.GetAsync(id);
            if (model == null) 
                return NotFound();

            await clientService.RemoveAsync(model.ToDTO());

            return RedirectToAction("Index");
        }
    }
}

ITHOOT/Controllers/PositionController.cs
using BLL.Core;
using Mapper;
using Microsoft.AspNetCore.Mvc;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ITHOOT.Controllers
{
    public class PositionController : Controller
    {
        IPositionService positionService;
        public PositionController(IPositionService positionService)
        {
            this.positionService = positionService;
        }
        public async Task<IActionResult> Index()
        {
            var model =await positionService.GetAllAsync();
            return PartialView(model.ToList());
        }
        [HttpGet]
        public IActionResult Create() => PartialView();
        [HttpPost]
        public async Task<IActionResult> Create(PositionModel model)
        {
            if (ModelState.IsValid)
            {
                await positionService.AddAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await positionService.GetAsync(id);
            return PartialView(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(PositionModel model)
        {
            if (ModelState.IsValid)
            {
                await positionService.UpdateAsync(model.ToDTO());
                return RedirectToAction("Index");
            }
            return PartialView(model);
        }
        [HttpPost] 
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty) return BadRequest();
            try
            {
                PositionModel model = await positionService.GetAsync(id);
                await positionService.RemoveAsync(model.ToDTO());
            }
            catch (Exception)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
    }
}

ITHOOT/Views/Position/Create.cshtml
@model PositionModel
<div class="row justify-content-center">
    <div class="col-md-8">
        <form asp-action="Create" onsubmit="return postQuery(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add new" class="btn btn-primary" />
            </div>
            <div>
                <a class="btn btn-sm btn-primary text-white" onclick="getRequest('@Url.Action("Index", "Client", null, Context.Request.Scheme)')">Return</a>
            </div>
        </form>
    </div>
</div>

ITHOOT/Views/Position/Edit.cshtml
@model PositionModel
<div class="row justify-content-center">
    <div class="col-md-8">
        <form method="post" asp-action="Edit" onsubmit=" return postQuery(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-sm btn-primary text-white" onclick="getRequest('@Url.Action("Index", "Position", null, Context.Request.Scheme)')">Return</a>
</div>

ITHOOT/Views/Position/Index.cshtml
@model IEnumerable<PositionModel>

<div>
    <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Create", "Position", null, Context.Request.Scheme)')">Add</a>
</div>
@foreach (PositionModel item in Model)
{
    <div class="d-flex flex-column bg-light m-2 justify-content-around">
        <div class="d-flex justify-content-between">
            <div class="d-flex">
                <p class="p-1">@Html.DisplayNameFor(model => model.Id)</p>
                <p class="p-1">@Html.DisplayFor(model => item.Id)</p>
            </div>
            <div class="d-flex">
                <p class="p-1">@Html.DisplayNameFor(model => model.Name)</p>
                <p class="p-1">@Html.DisplayFor(model => item.Name)</p>
            </div>
        </div>
        <div class="d-flex">
            <a class="btn btn-primary text-decoration-none pointer text-white" onclick="getRequest('@Url.Action("Edit", "Position", new { id = item.Id }, Context.Request.Scheme)')">Edit</a> |
            <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this);">
                <input class="btn btn-danger" type="submit" value="Delete" />
            </form>
        </div>
    </div>
}